services:
  mongo:
    container_name: namaste_sav_mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

  web:
    container_name: namaste_sav_express
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - mongo
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/namaste-savannah
      - SESSION_SECRET=localDevSecret
      - GMAIL_EMAIL
      - GMAIL_PASSWORD
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_BUCKET_NAME

volumes:
  mongodb:
  mongodb_config:
