name: Deploy Website

on: [push]

env:
  GCP_PROJECT: namaste-savannah
  IMAGE_NAME: main-website

jobs:
  generate-tag:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.tag.outputs.short_sha }}
    steps:
      - uses: actions/checkout@v2

      - name: Generate image tag
        id: tag
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

  publish-images:
    runs-on: ubuntu-latest
    needs: generate-tag
    env:
      IMAGE_TAG: ${{ needs.generate-tag.outputs.image-tag }}
    outputs:
      image: ${{ steps.generate_name.outputs.docker_image }}
    steps:
      - uses: actions/checkout@v2

      - name: Generate name and tag for Docker image
        id: generate_name
        run: echo "::set-output name=docker_image::gcr.io/$GCP_PROJECT/$IMAGE_NAME:$IMAGE_TAG"

      - name: Build Docker image
        run: |
          docker build -f Dockerfile.prod . -t "${{ steps.generate_name.outputs.docker_image }}"
          docker image ls

      - name: Publish Docker image
        run: |
          echo "Publishing Docker image gcr.io/$GCP_PROJECT/$IMAGE_NAME:$IMAGE_TAG ..."

  deploy-website-cloud-run:
    needs: publish-images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy Cloud Run
        run: |
          echo "Deploy service for image ${{ needs.publish-images.outputs.image }} ..."
      #   id: deploy
      #   uses: google-github-actions/deploy-cloudrun@main
      #   with:
      #     service: home-website
      #     image: gcr.io/namaste-savannah/main-website
      #     credentials: ${{ secrets.GCP_SA_KEY }}
      #     project_id: ${{ secrets.GCP_PROJECT }}

      # - name: Verify deployment
      #   run: curl "${{ steps.deploy.outputs.url }}" --fail --silent --show-error
