name: Deploy Website

on: [push]

env:
  HOSTNAME: gcr.io
  PROJECT_NAME: namaste-savannah
  IMAGE_NAME: main-website

jobs:
  generate-tag:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.tag.outputs.short_sha }}
    steps:
      - uses: actions/checkout@v2

      - name: Generate image tag
        id: tag
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

  publish-images:
    runs-on: ubuntu-latest
    needs: generate-tag
    env:
      IMAGE_TAG: ${{ needs.generate-tag.outputs.image-tag }}
    outputs:
      image: ${{ steps.generate_name.outputs.docker_image }}
    steps:
      - uses: actions/checkout@v2

      - name: Generate name and tag for Docker image
        id: generate_name
        run: echo "::set-output name=docker_image::$HOSTNAME/$PROJECT_NAME/$IMAGE_NAME:$IMAGE_TAG"

      - name: Build Docker image
        run: |-
          docker build -f Dockerfile.prod . -t ${{ steps.generate_name.outputs.docker_image }}
          docker image ls

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: $PROJECT_NAME
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Publish Docker image
        run: docker push ${{ steps.generate_name.outputs.docker_image }}

  deploy-website-cloud-run:
    needs: publish-images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: main-website
          image: ${{ needs.publish-images.outputs.image }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          project_id: $PROJECT_NAME

      - name: Verify deployment
        run: curl "${{ steps.deploy.outputs.url }}" --fail --silent --show-error
