name: Deploy Website

on: [push]

env:
  GCP_PROJECT: namaste-savannah
  IMAGE_NAME: main-website

jobs:
  publish-images:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.tag.outputs.short_sha }}
    steps:
      - uses: actions/checkout@v2

      - name: Generate image tag
        id: tag
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "::set-output name=short_sha::$SHORT_SHA"

      - name: Build Docker image
        run: |
          echo "Building Docker image gcr.io/$GCP_PROJECT/$IMAGE_NAME:$SHORT_SHA ..."
          echo ${{ steps.tag.outputs.short_sha }}

      - name: Publish Docker image
        run: |
          echo "Publishing Docker image gcr.io/$GCP_PROJECT/$IMAGE_NAME:$SHORT_SHA ..."

  deploy-website-cloud-run:
    needs: publish-images
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ needs.publish-images.outputs.image-tag }}
    steps:
      - uses: actions/checkout@v2

      - name: Deploy Cloud Run
        run: |
          echo "Deploy service for image gcr.io/$GCP_PROJECT/$IMAGE_NAME:${{ needs.publish-images.outputs.image-tag }} ..."
          echo ${{ needs.publish-images.outputs }}
          echo $IMAGE_TAG
      #   id: deploy
      #   uses: google-github-actions/deploy-cloudrun@main
      #   with:
      #     service: home-website
      #     image: gcr.io/namaste-savannah/main-website
      #     credentials: ${{ secrets.GCP_SA_KEY }}
      #     project_id: ${{ secrets.GCP_PROJECT }}

      # - name: Verify deployment
      #   run: curl "${{ steps.deploy.outputs.url }}" --fail --silent --show-error
